app:
  restart: always
  build: ./app
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -b :8000 "app:create_app()"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app
